version: '2.0'
services:
  mqttweb:
    image: nginx
    container_name: mqttweb
    ports:
      - '8186:80'
    volumes:
      - './www:/usr/share/nginx/html:ro'
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ./mqtt:/mosquitto
    ports:
      - 1884:1883 #mqtt
      - 8185:8000 #websockets
